### ISSUE TITLE
Kalibrierung für Ersatz-Anemometer für die Funk-Wetterstation WS1080 und WS3080

### ISSUE THREAD

**Issue by Xento** [jp112sdl/HB-UNI-Sen-WEA#11]
Ich habe mal die Kalibrierungsdaten für das oben genannte Ersatzteil von ELV ausgeklügelt.
Die Daten habe ich mit Hilfe der Freetec Wetterstation von Pearl ermittelt.
Diese ich bis auf das Funkprotokoll baugleich mit der WS1080, daher ist es auch das gleiche Windrad.

Damit immer der gleiche Wind auf das Windrad trifft, habe ich das Anemometer abwechselnd mit der Wetterstation und dem Homematic Sensor verbunden und die Werte verglichen.
Folgende Werte sind dabei rausgekommen:
Radius: 7 cm
Kalbrierungsfaktor: 1.5

Vielleicht kann man eine Liste mit Werten für verschiedene Anemometer bereitstellen.
Wenn jemand keinen Windmesser oder eine andere Referenz hat, ist es quasi unmöglich die richtigen Werte zu finden.

**Comment by jp112sdl** [comment]
Besten Dank! Bin noch am Überlegen, wo ich diese Informationen am besten platziere...

**Comment by jp112sdl** [comment]
https://github.com/jp112sdl/HB-UNI-Sen-WEA/wiki/Kalibrierungsdaten_Sensoren
