### ISSUE TITLE
Nachrichten werden mit NACK von anderem AsksinPP-Aktor beantwortet

### ISSUE THREAD

**Issue by Xento** [jp112sdl/HB-UNI-Sen-WEA#12]
Ich habe gerade zufällig festgestellt, dass irgendwie komische Nachrichten gesendet werden.

Der Wettersensor ist mit meinem RolloAktor (auch mit AskSinPP) gepeert so dass dieser runter fährt wenn ne Windböhe kommt.

Hier ein Auszug aus der Log vom Rolloaktor:
```
-> 0D 05 A0 53 F1D002 5932AF 41 00 00 C7  - 254183
<- 0A 05 80 02 5932AF F1D002 80  - 254298
-> 0D 05 A0 53 F1D002 5932AF 41 00 00 C7  - 254337
<- 0A 05 80 02 5932AF F1D002 80  - 254459
-> 0D 05 A0 53 F1D002 5932AF 41 00 00 C7  - 254498
<- 0A 05 80 02 5932AF F1D002 80  - 254619
-> 0D 05 A0 53 F1D002 5932AF 41 00 00 C7  - 254652
<- 0A 05 80 02 5932AF F1D002 80  - 254769
-> 0D 05 A0 53 F1D002 5932AF 41 00 00 C7  - 254803
<- 0A 05 80 02 5932AF F1D002 80  - 254918
-> 0D 05 A0 53 F1D002 5932AF 41 00 00 C7  - 254957
<- 0A 05 80 02 5932AF F1D002 80  - 255078
-> 0C 06 A2 41 F1D002 5932AF 01 01 C8  - 255281
jumpToTarget: 6 1
setDestLevel: 0
Switch from 06 to 04
getNextState: 4
Switch from 04 to 05
<- 0E 06 80 02 5932AF F1D002 01 01 00 40 58  - 255401
getNextState: 5
calcDriveTime: 420 - 0 - 20
Switch from 05 to 09
DOWN - 255823
getNextState: 9
Switch from 09 to 06
STOP - 257853
```

Der Asksin Aktor schickt scheinbar irgendwas falsches auf diese Nachricht zurück ...

**Comment by Xento** [comment]
Ah ich habe gerade festgestellt, das 0A 05 80 02 5932AF F1D002 80 ein NACK ist.
Das währe jetzt was für @pa-pa aber sollte, danach nicht weiter versucht werden die Nachricht erneut zu senden?

**Comment by jp112sdl** [comment]
Hmm, wäre es dann evtl. eher ein Ticket für die AskSinPP Lib?

Von der Wetterstation kommt als COND_VALUE `C8` (200).

Ich hab die Wetterstation bisher nur mit einem originalen HM Zwischenstecker gepeert und da ist das Verhalten korrekt.

Falls du die Möglichkeit hast, könntest du als Gegenprobe mal einen Tastensender peeren. Der verhält sich m.W. genau so und sendet 200 an den Aktor.
Dann könntest du dort mal schauen, wie der Reply vom Rollladenaktor aussieht.

**Comment by jp112sdl** [comment]
Ich wollte gerade fragen, welchen Stand dein eingesetzter Wetterstations-Sketch hat 😄 
Denn der geht nur, wenn du die aktuelle AskSinPP nutzt mit eben genanntem Commit.
Die ExtraMessages werden seither nämlich nur noch direkt an die Zentrale gesendet.

**Comment by Xento** [comment]
Werd ich morgen mal machen ;-)

**Comment by Xento** [comment]
Soo, AskSinPP war schon auf dem aktuellen Stand, nur der Sketch nicht.

Hab da noch nen paar Offtopic Punkte:
1. Ich sollte mich glaube ich mal mit dem OTA-Bootloader beschäftigen, dann muss ich mich nicht immer an die Geräte stöpseln.
Funktioniert das eigentlich mit der CCU?

2. Mir ist aufgefallen, dass der Sketch für einen Arduino mit dem normalen Bootloader zu groß ist.
Die IDE sagt es währen 102% belegt.
Wenn man das Debugging deaktiviert dann sind noch 93% frei.
Zum Glück habe ich auf diesem Arduino schon den OptiBootloader drauf.

**Comment by jp112sdl** [comment]
> Ich sollte mich glaube ich mal mit dem OTA-Bootloader beschäftigen, dann muss ich mich nicht immer an die Geräte stöpseln.
Funktioniert das eigentlich mit der CCU? 

Ja, aber ob der Arduino per Funkbefehl in den Bootloader-Modus wechselt, weiß ich nicht.
Ich habe da nichts weiter implementiert und auch bisher nur 1-2 Mal mit OTA experimentiert.
Da ich gern nach dem Flashen noch kurz die Debugmeldungen sehen möchte, bleibe ich bei der Turnschuhvariante. 😄 

> Mir ist aufgefallen, dass der Sketch für einen Arduino mit dem normalen Bootloader zu groß ist. Die IDE sagt es währen 102% belegt.

Welche Arduino IDE Version benutzt du?
Mit der 1.8.5 wird der Sketch zu groß. Ich nutze die 1.8.1 -> damit passt alles. Ohne Veränderung des Bootloaders.

> Wie bringt man der CCU bei, dass das Gerät eine neue Firmwareversion hat?
Musste nachdem ich das Addon aktualisiert hatte, den Sensor einmal ablernen und wieder anlernen.

Drüberlernen würde ausreichen, um die Versionsinformation an sich upzudaten.
Aber wenn neue Werte-Parameter hinzukommen, bleibt leider nix weiter übrig, als das Gerät komplett neu anzulernen. Das ist aber ein "Problem" der ReGa.
