### ISSUE TITLE
slightly better parameter check of pwmval overflow in raindetector_heater

### ISSUE THREAD

**Issue by harvey637** [jp112sdl/HB-UNI-Sen-WEA#13]
Hallo Jerome,
ist das optimal?

in funktion raindetector_heater:
...
if (State == true) {
  if pwmval < 255) pwmval = pwmval + 51;
} else
...

Alles richtig, es wird bei jedem Durchlauf pwmval um 51 erhöht, also 0 - 51 - 102 - 153 - 204 - 255.
Also passt < 255, weil ja nach dem 5. Durchlauf keine Erhöhung mehr stattfindet.

Will man da spielen könnte ein "#define PWMHEATER_DELTA 51" das ganze variabel gestalten, 
also den Anstieg der Erwärmung z.b. flacher einstellen. Dann spätestens wäre es besser, etwa mit 

#define PWMHEATER_DELTA 30 // zusätzliche Erwaermung der Regendetektorheizung je Durchlauf 
(RAINDETECTOR_CHECK_INTERVAL)

...
if ((pwmval + PWMHEATER_DELTA) > 255) {
   pwmval = 255;
} else {
   pwmval = pwmval + PWMHEATER_DELTA;
}
...

das ganze (im Sketch) konfigurierbar und korrekt geprüft zu gestalten.
Sorry, sind wieder ein paar Byte mehr :-( Aber auch ohne define finde ich das if ... then ... else besser.
cu
Harvey

**Comment by jp112sdl** [comment]
Ja, das kann jeder spielen wie er möchte.
Grundanliegen der PWM-Ansteuerung war, dass die Spannung beim Einschalten der Heizung nicht einbricht.

Btw.: Würde die Bedingung `(pwmval + PWMHEATER_DELTA) > 255` überhaupt erfüllt werden, so lange `pwmval` ein `uint8_t` ist?

Und wegen der paar Byte mehr -> wenn man einen kleineren (oder gar keinen) Bootloader auf den Pro Mini flasht, hat man noch gut Luft nach oben.

**Comment by harvey637** [comment]
Hallo Jerome,
danke für die schnelle Antwort!

Vermutung: das "pwmval + PWMHEATER_DELTA" ist erstmal unabhängig von uint_8, ich test das mal, nur zum eigenen Verstandnis.

Genauso habe ich das mit dem langsamen Anheizen auch vermutet (Grund für ansteigenden PWM).
Eine Kleinigkeit fällt mir noch ein:
Könnte es sinnvoll sein, die zeitliche Länge des Heizens zu beschränken? Eventuell
liegt ein Blatt drauf oder eine Frucht ist drauf gefallen und geplatzt. Auch der Taupunkt könnte
ziemlich lange im HEAT_DEWFALL_T bleiben. In der Summe sicherlich verschmerzbar (Stromkosten),
aber der Sensor freut sich bestimmt drüber. Ich denke für mich auch über einen reinen
Regensensor nach, der dann ohne device.xml funktioniert und Heizung per Funk
geschaltet werden kann, ein von xxx Projektchen.
Neben dem (erfolgreich abgeschlossenen) LCD-Anzeige von Temperatursensoren und dem
ebenfalls (aber sehr quick_n_dirty) abgeschlossenen Dallas-Sensoren mit SENSOR_ID (aus user_byte)
anstatt der SENSOR_ADDR. Beispiele dazu in DallasTemperature gefunden.
Danke und ciao
Harvey

**Comment by jp112sdl** [comment]
> Könnte es sinnvoll sein, die zeitliche Länge des Heizens zu beschränken?

Ist mir bisher noch gar nicht in den Sinn gekommen.

> aber der Sensor freut sich bestimmt drüber. 

Mit ~50°C von unten dauerhaft beheizt zu werden, ist denke ich kein Problem für die Platine.

>  Auch der Taupunkt könnte ziemlich lange im HEAT_DEWFALL_T bleiben. 

Ja, manchmal die halbe Nacht bei mir. Aber dann bleibt halt die Heizung an. Ist mir lieber, als eine Regen-Falschmeldung (die ich bisher noch **nie** hatte!) zu bekommen.

>  Ich denke für mich auch über einen reinen
Regensensor nach, der dann ohne device.xml funktioniert und Heizung per Funk
geschaltet werden kann, ein von xxx Projektchen.

Ja, sollte kein Problem sein den HM-Sen-RD-O nachzubilden.
Und der hat ja einen Kanal zum Schalten der Heizung.
