### ISSUE TITLE
Abdeckung für UV Sensor VEML6070

### ISSUE THREAD

**Issue by spaceduck518** [jp112sdl/HB-UNI-Sen-WEA#14]
wie habt ihr die die wasserfeste Abdeckung für den UV Sensor realisiert? Alle mir bekannten transparenten Kunststoffe filtern UV Strahlung, da dürfte am Sensor nicht mehr viel ankommen.

**Comment by jp112sdl** [comment]
Hi,

für allgemeine Diskussionen bitte das Homematic Forum benutzen.
Es gibt hier einen Beitrag zum dem Wettersensor:
https://homematic-forum.de/forum/viewtopic.php?f=76&t=44245&start=390
Du kannst auch gern einen neuen Beitrag erstellen.

Hier erreichst du vorrangig nur mich als Entwickler...
Ich benutze eine kleines Gewürzglas.
Gabs mal als Adventkalender:
https://www.discounto.de/Angebot/Erlesene-Gewuerz-Selection-Adventskalender-955697/

LG,
Jérôme
