### ISSUE TITLE
Regenmelder Sensorplatine anschließen

### ISSUE THREAD

**Issue by Alveran81** [jp112sdl/HB-UNI-Sen-WEA#15]
Hallo,

bin gerade dabei die Wetterstation nachzubauen. Habe zunächst Arduino, BME280, CC1101 und Anemometer angeschlossen und einen Funktionstest gemacht. Werte kommen sauber auf der Homematic an. 
Ich habe mir wie empfohlen diesen Regensensor gekauft. https://www.stall.biz/produkt/regenmelder-sensorplatine
Leider finde ich keinen Anschlussplan oder technische Daten. Wird dieser mit 5V betrieben und wie verbinde ich den Arduino damit?  Laut Schaltplan steht was von Pin9. Soll ja nicht die ganze zeit beheizt werden sondern nur wenn es regnet. 
Also verstehe ich richtig, Dauerplus liegt immer an, die Masse für über den Transistor der an Pin neun hängt geschalten und dann müssen doch eigentllich noch zwei Messleitung verbunden werden?
![20181028_142811](https://user-images.githubusercontent.com/25667147/47616504-022dd680-dabe-11e8-957f-a28f700b24d4.jpg)

**Comment by jp112sdl** [comment]
Hi,

![wir](https://raw.githubusercontent.com/jp112sdl/HB-UNI-Sen-WEA/master/Images/wiring.png) 

Es geht der 
- **rot-weiße** Draht an **+ Heizung**, der 
- **orange-weiße** an **- Heizung**, 
- **schwarz** (GND) an **A vom Sensor** und 
- **orange** geht an **B vom Sensor**.

Bei der Heizung wird wie schon richtig erkannt, +5V dauerhaft anliegen und die Heizung über den NPN Transistor an Pin 9 bei Bedarf eingeschaltet.

**Comment by Alveran81** [comment]
Jetzt habe ich es verstanden. Vielen Dank. 
Vielleicht kann man das in der Grafik noch ergänzen (schwarz (GND) an A vom Sensor und
orange geht an B vom Sensor.)

**Comment by jp112sdl** [comment]
Ich dachte, die Grafik (Sensorfläche an schwarz/orange) wäre ausreichend. ;)

**Comment by Alveran81** [comment]
War mir nicht ganz klar und da ich kein Datenblatt zum Sensor gefunden habe wollte ich lieber nochmal fragen bevor es einmal kurz raucht. 😁

**Comment by jp112sdl** [comment]
A und B sind nicht leitend miteinander verbunden, da kann nix passieren.
Bei der Heizung passiert bei Verpolung einfach gar nix... 😄
