### ISSUE TITLE
fehlende Libs

### ISSUE THREAD

**Issue by Xento** [jp112sdl/HB-UNI-Sen-WEA#7]
Hi, 
ich möchte mir auch soeine Wetterstation bauen und habe versucht den Sketch zu compilern.
Leider fehlen die Bibliotheken für 
#include <sensors/Max44009.h>
#include <sensors/Veml6070.h>

Für Max44009 konnte wahrscheinlich die richtige Lib finden, allerdings will Veml6070 nicht.
Ich nutze die Arduino IDE zum compilern.
Könntest du Links zu den verwendeten Bibliotheken reinstellen?

**Comment by jp112sdl** [comment]
Hi,

lade dir bitte mal die aktuelle master der AskSinPP Library.
Dort sind die Sensorklassen für den Max44009 und Veml6070 mit drin.
Es werden **keine** gesonderten Bibliothek benötigt.

Siehe auch: https://github.com/jp112sdl/HB-UNI-Sen-WEA/wiki/Code

**Comment by Xento** [comment]
Ah super. Dann muss ich mal alles aktualisieren.
