### ISSUE TITLE
BIDI bei WeatherEventMsg?

### ISSUE THREAD

**Issue by Xento** [jp112sdl/HB-UNI-Sen-WEA#9]
Ist er richtig so, dass die WeatherEventMsg bidirektional gesendet werden?
Seitdem ich einen Windsensor gebaut habe ist auch bei 60 sekündiger Meldung der DC der CCU ziehmlich angestiegen.
Will mir noch einen zweiten Wettersensor mit allen Sensoren bauen, dann währe die CCU schon ziehmlich an ihrere Grenze.

**Comment by jp112sdl** [comment]
Echt? 😱 
Ich sende alle 30 Sekunden und da passiert nix am DC.
Eigentlich wird nur jede [20. Meldung per BIDI gesendet, sonst per BCAST](https://github.com/jp112sdl/HB-UNI-Sen-WEA/blob/7250f011d05615f5691bec8c287be622bd283e45/HB-UNI-Sen-WEA.ino#L360).
Oder hab ich einen Denkfehler?

Aber bei mir liegt der DC konstant zwischen 5-9%

**Comment by jp112sdl** [comment]
![Uploading Bildschirmfoto 2018-08-16 um 10.51.04.png…]()

Habs gerade noch mal gecheckt. Arbeitet korrekt.

**Comment by Xento** [comment]
Ok, soweit hab ich noch nicht in den Code geschaut.
Hatte nur das BIDI bei der Message gesehen.
Das BIDI wird zurückgesetzt wenn man das per broadcast sendet.
Dann muss ich mal weiter rumprobieren warum der DC nun so hoch ist bei mir ...

**Comment by jp112sdl** [comment]
Ja genau, `broadcastPeerEvent()` sendet automatisch per BCAST.
